# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BottoneCiaoPorco.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets

import FileA
import FileB


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(507, 153)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Bottone_Ciao = QtWidgets.QPushButton(self.centralwidget)
        self.Bottone_Ciao.setGeometry(QtCore.QRect(20, 10, 231, 91))
        self.Bottone_Ciao.setObjectName("Bottone_Ciao")
        self.Bottone_Ciao.clicked.connect(self.Ciao)
        self.Bottone_Porco = QtWidgets.QPushButton(self.centralwidget)
        self.Bottone_Porco.setGeometry(QtCore.QRect(260, 10, 231, 91))
        self.Bottone_Porco.setObjectName("Bottone_Porco")
        self.Bottone_Porco.clicked.connect(self.Porco)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 507, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Bottone_Ciao.setText(_translate("MainWindow", "Premi per aprire l\'applicazione \"FileA.py\""))
        self.Bottone_Porco.setText(_translate("MainWindow", "Premi per aprire l\'applicazione \"FileB.py\""))

    def Porco(self):
        FileB.Porco()

    def Ciao(self):
        FileA.Ciao()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
